version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      postgres-local-network: { }

networks:
  postgres-local-network:
    name: postgres-local-network
    driver: bridge